# Generated by Django 5.1.2 on 2025-01-12 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sellers", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="seller",
            name="slug",
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
    ]
