# Generated by Django 5.1.2 on 2025-02-15 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
