# Generated by Django 5.1.2 on 2025-01-12 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_remove_user_is_marketer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="purchases",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
