# Generated by Django 5.1.2 on 2024-10-31 21:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(max_length=2000)),
                (
                    "price",
                    models.FloatField(
                        validators=[django.core.validators.MinValueValidator(0.01)]
                    ),
                ),
                ("sales", models.PositiveIntegerField(default=0)),
                ("stock", models.PositiveIntegerField(default=0)),
                ("sub_date", models.DateTimeField(auto_now_add=True)),
                ("in_warehouse", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
    ]
