# Generated by Django 5.1.2 on 2025-01-29 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carts", "0002_alter_cart_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="total_sum",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
